### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by raananraz** [noctarius/snowcast#1]
Hi, 
Can you please add your project to a maven repository?
Thanks!

**Comment by noctarius** [comment]
Sure, haven't done it yet since migration is still missing. Are snapshots ok for you for now? :)

**Comment by raananraz** [comment]
sure .that would be great!

**Comment by noctarius** [comment]
Here's the Maven snapshot repository https://github.com/noctarius/snowcast#maven-coordinates

Interfaces still need Javadoc, after that I might give it a try for a RC :)
