### ISSUE TITLE
disable banner

### ISSUE THREAD

**Issue by mozinrat** [noctarius/snowcast#13]
How to disable below banner
   _________  ____ _      ___________ ______/ /_
  / **_/ __ \/ __ \ | /| / / ___/ __ `/ ___/ __/
 (**  ) / / / /_/ / |/ |/ / /__/ /_/ (__  ) /_  
/____/_/ /_/____/|__/|**/_**/__,_/____/__/  

snowcast node mode -  version: 1.0.0-RC3    build-date: 2015-06-23 06:10

WARNING: LAZY CONFIGURATION USED! DO NOT DO THIS IN PRODUCTION!

**Comment by noctarius** [comment]
You can either set it at runtime:

```
System.setProperty("snowcast.logo.disable", "true");
```

or using JVM parameter:

```
java ... -Dsnowcast.logo.disable=true
```

The warning has a different reason, since you use lazy configuration. You should explicitly configure snowcast before starting the Hazelcast node using the SnowcastNodeConfigurator.
