### ISSUE TITLE
Please consider changing SnowcastEpoch initialization examples

### ISSUE THREAD

**Issue by lukasherman** [noctarius/snowcast#17]
I would recommend changing the initialization examples to be time zone aware. Current example code prevents second node running in different time zone from joining.

A recommended way is:
```
Calendar calendar = GregorianCalendar.getInstance(TimeZone.getTimeZone("UTC"));
calendar.set(2017, Calendar.JANUARY, 1, 0, 0, 0);
SnowcastEpoch epoch = SnowcastEpoch.byCalendar(calendar);
```
or Java 8 like:
```
ZonedDateTime utc = ZonedDateTime.of(2017, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC);
SnowcastEpoch epoch = SnowcastEpoch.byTimestamp(utc.toInstant().toEpochMilli());
```

**Comment by noctarius** [comment]
Great catch, do you mind creating the necessary changes in docs / javadoc and make a pull request? :) also happy to introduce java 8 classes into the api for 2.0 versions, limiting it to min Java 8

**Comment by lukasherman** [comment]
Okay, I will arrange it. What about introducing a new static builder method?
```
SnowcastEpoch.byInstant(Instant instant);
```
It might open additional opportunities in offset calculation, based on Instant epoch-seconds instead.
