### ISSUE TITLE
localNext() for better data locality

### ISSUE THREAD

**Issue by lukasherman** [noctarius/snowcast#20]
Generator should natively support data locality. When generated id is used directly as map key, a dedicated method should provide a key, which is local to the calling member. Is is a good idea? 
A simple do/while loop in the calling code can achieve that functionality, but I guess there can be better way to generate local ids.

**Comment by noctarius** [comment]
Why do you think that makes a huge impact? The id is generated once (I guess you mean node id?).

**Comment by lukasherman** [comment]
I mean, to make sure the map entry created will be stored stored and processed on local member, I have to ensure the value returned by sequencer goes to local partition. 
```  
  do {
    id = sequencer.next();
    isLocal = hazelcastInstance.getPartitionService().getPartition(id).getOwner().localMember();
  } while (!isLocal);
```
Does it make sense?

**Comment by noctarius** [comment]
Tbh I don't think that would bring a lot of benefits for a one time operation and the benefit is gone as soon as the cluster topology changes.

**Comment by JuKu** [comment]
I think this feature will increase unneccessary performance overhead, because of while loop.

**Comment by lukasherman** [comment]
Okay I understand that. It makes sense in my use case (request-response matching) to generate local ids. 
Anyway, looking at the source code around `AbstractSequencerContext.next()`, there is already some loop, checking nextId for validity. The method to identify that the Long id is local goes thru `Data.getPartitionHash()` over `hashToIndex` to `partitionMap`. There might be some code shortcut to that, built-in directly into sequencer.localNext() method. 
But nevermind, thanks for your opinion on that.

**Comment by noctarius** [comment]
The way it works is (and that is the only remote operation), when you start a node / client, it'll join the cluster to get a node id assigned. That node id will be used as long as the node or client is up. After that all operations are completely local to the node / client, that is the main idea. That means, on the other side, that the number of ids to be generated per millisecond is limited. That is the internal loop to make sure, if we exceed the local max, we need to spin for the next millisecond.

But maybe I don't know what loop your looking at, since AbstractSequencerContext doesn't even know about the Hazelcast bits, except for attach (called hopefully only once :-)) and detach (same guess here).

**Comment by lukasherman** [comment]
I understand that.
What I want to ensure is that value returned by `key = NodeSequencer.next()` followed by call `map.put(key, Object)` guarantees that the `Object` is stored in node local, not remote partition.

**Comment by noctarius** [comment]
Oh I see, sorry took a while to understand your use case. The problem with that is, you can exceed the locally produceable IDs extremely quickly. In general this system was more designed for IDs in games, however I guess you could just put another loop around the next call to retrieve IDs over and over again. In this use case, however, I'd either go for UUIDs or for a complex key with a "PartitionAware" implementation, returning a key which is local to one of the nodes partitions.

**Comment by lukasherman** [comment]
Yes, there is clear tradeoff between data locality and throughput, even chance to get correct ID decreases when number of nodes grows. I better leave this idea.
Thanks for your input.
Regards
